version: '3.9'

services:
  app:
    image: flask_app:latest
    container_name: flask_app
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DB_HOST: flask_mysql
      DB_NAME: flask
      DB_USER: flask
      DB_PASSWORD: password
    ports:
      - "5000:5000"
    depends_on:
       - mysql

      

  mysql:
    container_name: flask_mysql
    image: mysql:latest
    restart: unless-stopped
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: flask
      MYSQL_USER: flask
      MYSQL_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db/mysqld.cnf:/etc/mysql/mysql.conf.d/mysqld.cnf
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: flask_phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_USER: flask
      PMA_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "8080:80"
    depends_on:
      - mysql
  flask_tests:
    build:
      context: ./test
      dockerfile: Dockerfile
    container_name: flask_tests
    depends_on:
       - app
      
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "test.py"]

volumes:
  mysql-data:
    driver: local
