name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: SSH to EC2 and deploy
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          echo "Updating code on EC2..."
          cd ~/flask_project || mkdir -p ~/flask_project
          git fetch --all
          git reset --hard origin/main

          echo "Building Docker images..."
          docker-compose -f ~/flask_project/docker-compose.yml build

          echo "Starting containers..."
          docker-compose -f ~/flask_project/docker-compose.yml up -d

          echo "Deployment complete!"

